services:
  postgres:
    image: postgres:16
    container_name: crypt-local-database
    env_file: ./.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
